### ISSUE TITLE
Unable to remove focus from textfield

### ISSUE THREAD

**Issue by Rohith-JN** [Rohith-JN/Tasks#3]
Cannot remove focus from Title-Textfield in [TodoScreen](https://github.com/Rohith-JN/Tasks-Android/blob/main/lib/View/TodoScreen.dart) 
Unable to dismiss onScreen keyboard
For more info: [Stackoverflow](https://stackoverflow.com/questions/74541604/not-able-to-remove-focus-from-input-field)

**Comment by kiarash-nazari** [comment]
I sent a pull request and I think it will help you.
